version: "3"

services:
  manager:
    build:
      context: Manager
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - nginx
  worker:
    build:
      context: Worker
      dockerfile: ./Dockerfile
    scale: ${WORKERS_AMOUNT}
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8001:8001"
    expose:
      - "8001"
    depends_on:
      - worker