version: "3"

services:
  manager:
    build:
      context: Manager
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb1
    environment:
      - WORKERS_AMOUNT
      - PROXY_URL
  worker:
    build:
      context: Worker
      dockerfile: ./Dockerfile
    scale: ${WORKERS_AMOUNT}
    environment:
      - MANAGER_URL
    expose:
      - "8002"
  mongodb1:
    image: mongo:4
    restart: always
    logging:
      driver: none
    volumes:
      - mongodata1:/data/db
    expose:
      - "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1"]
  mongodb2:
    image: mongo:4
    restart: always
    logging:
      driver: none
    volumes:
      - mongodata2:/data/db
    expose:
      - "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1"]
  mongodb3:
    image: mongo:4
    restart: always
    logging:
      driver: none
    volumes:
      - mongodata3:/data/db
    expose:
      - "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1"]    
  mongosetup:
    image: "mongo-setup"
    build: "./mongo-setup"
    container_name: "mongosetup"
    depends_on:
      - mongodb1
    volumes:
      - mongostatus:/data/
      
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
volumes:
  mongodata1:
  mongodata2:
  mongodata3:
  mongostatus: